config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "/", to: "bmr_calculator#index"
  post '/calculate', to: 'bmr_calculator#calculate'
  root "bmr_calculator#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bmr_calculator_controller.rb
class BmrCalculatorController < ApplicationController
	def index
	end

	def calculate
		@age = params[:age]
		@height = params[:height]
		@weight = params[:weight]
		@gender = params[:gender]
		if @gender == 'male'
			# original method
			# @bmr = 66.5 + (13.75*@weight.to_i) + (5.003*@height.to_i) - (6.755*@age.to_i)

			# revised method
			@bmr = (10*@weight.to_i)+(6.25*@height.to_i)-(5*@age.to_i)+5
		elsif @gender == 'female'
			# original method
			# @bmr = 655.1 + (9.563*@weight.to_i) + (1.850*@height.to_i) - (4.676*@age.to_i)

			# revised method
			@bmr = (10*@weight.to_i)+(6.25*@height.to_i)-(5*@age.to_i)-161
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bmr_calculator_helper.rb
module BmrCalculatorHelper
end

app/views/bmr_calculator/calculate.html.erb
<h3>Your BMR is <%=@bmr%> kcal/day</h3>
<a href="/">
	<button type="button" class="btn btn-info">
		Back
	</button>
</a>

app/views/bmr_calculator/index.html.erb
<div class="col-md-12 col-xs-12 col-sm-12">
	<%= form_tag calculate_path do %>
		<div class="row">
			<span class="col-md-1 col-sm-3 col-xs-6">Age: </span>
			<span class="col-md-6 col-sm-12 col-xs-12"><%= text_field_tag "age", params[:age], placeholder: 'Enter the age',:class => 'form-control' %></span>
			<span class="col-md-3 col-sm-6 col-xs-12"> Years </span>
		</div>
		<br>
		<div class="row">
			<span class="col-md-1 col-sm-3 col-xs-6">Gender: </span>
			<span class="col-md-3 col-sm-6 col-xs-12">
				<input type="radio" name="gender" value="male"> Male
			  <input type="radio" name="gender" value="female"> Female
			</span>
		</div>
		<br>
		<div class="row">
			<span class="col-md-1 col-sm-3 col-xs-6">Height: </span>
			<span class="col-md-6 col-sm-12 col-xs-12"><%= text_field_tag "height", params[:height], placeholder: 'Enter the height',:class => 'form-control' %></span>
			<span class="col-md-3 col-sm-6 col-xs-12"> in cm </span>
		</div>
		<br>
		<div class="row">
			<span class="col-md-1 col-sm-3 col-xs-6">Weight: </span>
			<span class="col-md-6 col-sm-12 col-xs-12"><%= text_field_tag "weight", params[:weight], placeholder: 'Enter the weight',:class => 'form-control' %></span>
			<span class="col-md-3 col-sm-6 col-xs-12"> in kg </span>
		</div>
		<br>
		<div class="row col-md-3"><%= submit_tag 'Calculate Bmr', :class => 'form-control btn btn-success', :style => 'margin-left: 85%;' %></div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BmrCalculator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>